terminate called after throwing an instance of 'std::runtime_error'
  what():  dettrace runtime exception: we don't support rt_sigaction's SA_RESETHAND flag
Aborted (core dumped)
