terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported system call: alarm()

